"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const role_controllers_1 = require("../controllers/role.controllers");
const router = (0, express_1.Router)();
router.post('/roles', role_controllers_1.createRole);
router.get('/roles', role_controllers_1.getAllRoles);
router.get('/roles/:id', role_controllers_1.getRole);
router.put('/roles/:id', role_controllers_1.updateRole);
router.delete('/roles/:id', role_controllers_1.deleteRole);
exports.default = router;
